workspace = { members = [ "ProjRustComCargo3","ProjetoRustComCargo", "ProjetoRustComCargo2"] }
[package]
name = "CursoDesafioRUST_Youtube"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
